# Copy this file to secrets.yaml and fill in the values
# DO NOT COMMIT secrets.yaml TO GIT

backend:
  secrets:
    RESEND_API_KEY: "re_..."
    CLERK_WEBHOOK_SECRET: "whsec_..."
    SUPABASE_URL: "https://....supabase.co"
    SUPABASE_SERVICE_ROLE_KEY: "ey..."
    UPSTASH_REDIS_REST_URL: "https://....upstash.io"
    UPSTASH_REDIS_REST_TOKEN: "ey..."
